name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [sit, uat]  # Define environments

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y jmeter  # Install JMeter

    - name: Define environment-specific URL
      run: |
        if [ "${{ matrix.environment }}" == "sit" ]; then
          echo "URL=restful-booker.herokuapp.com" >> $GITHUB_ENV
        elif [ "${{ matrix.environment }}" == "uat" ]; then
          echo "URL=UAT-restful-booker.herokuapp.com" >> $GITHUB_ENV
        fi

    - name: Run JMeter tests in ${{ matrix.environment }} environment
      run: |
        jmeter -n -t APITTest.jmx -Jurl=${{ env.URL }} -l results_${{ matrix.environment }}.jtl
      env:
        JMETER_ENV: ${{ matrix.environment }}

    - name: Upload JMeter Test Results for ${{ matrix.environment }} environment
      uses: actions/upload-artifact@v2
      with:
        name: results-${{ matrix.environment }}
        path: results_${{ matrix.environment }}.jtl
